apiVersion: v1
kind: ConfigMap
metadata:
  name: prow-plugins
data:
  plugins.yaml: | {{- nindent 4 (toYaml .Values.configMap.plugins) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prow-config
data:
  config.yaml: | {{- nindent 4 (toYaml .Values.configMap.config) }}
