apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prow
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: prow-deck
              servicePort: 80
          - path: /hook
            pathType: Prefix
            backend:
              serviceName: prow-hook
              servicePort: 8888
