apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prow
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prow-deck
                port:
                  number: 80
          - path: /hook
            pathType: Prefix
            backend:
              service:
                name: prow-hook
                port:
                  number: 8888
