{{- if .Values.secret.githubToken.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: prow-github-token
stringData:
  token: {{.Values.secret.githubToken.value}}
{{- end }}
---
{{- if .Values.secret.hmacToken.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: prow-hmac-token
stringData:
  hmac: {{.Values.secret.githubToken.value}}
{{- end }}
---
{{- if .Values.secret.gcsCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: prow-gcs-credentials
stringData:
  service-account.json: {{.Values.secret.gcsCredentials.value}}
{{- end }}
