kind: ServiceAccount
apiVersion: v1
metadata:
  name: "prow-deck"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-deck"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "prow-deck"
subjects:
  - kind: ServiceAccount
    name: "prow-deck"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-deck-for-test"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "prow-deck-for-test"
subjects:
  - kind: ServiceAccount
    name: "prow-deck"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-deck"
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - get
      - list
      - watch
      # Required when deck runs with `--rerun-creates-job=true`
      # **Warning:** Only use this for non-public deck instances, this allows
      # anyone with access to your Deck instance to create new Prowjobs
      # - create
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-deck-for-test"
rules:
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "prow-horologium"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-horologium"
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - create
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-horologium"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "prow-horologium"
subjects:
  - kind: ServiceAccount
    name: "prow-horologium"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "prow-sinker"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-sinker"
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - delete
      - list
      - watch
      - get
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNames:
      - prow-sinker-leaderlock
    verbs:
      - get
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - prow-sinker-leaderlock
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - create
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-sinker-for-test"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
      - watch
      - get
      - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-sinker"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "prow-sinker"
subjects:
  - kind: ServiceAccount
    name: "prow-sinker"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-sinker-for-test"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "prow-sinker-for-test"
subjects:
  - kind: ServiceAccount
    name: "prow-sinker"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "prow-hook"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:

  name: "prow-hook"
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-hook"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "prow-hook"
subjects:
  - kind: ServiceAccount
    name: "prow-hook"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "prow-tide"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-tide"
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - create
      - list
      - get
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-tide"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "prow-tide"
subjects:
  - kind: ServiceAccount
    name: "prow-tide"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "prow-statusreconciler"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-statusreconciler"
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "prow-statusreconciler"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "prow-statusreconciler"
subjects:
  - kind: ServiceAccount
    name: "prow-statusreconciler"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prow-controller-manager
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-controller-manager
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    resourceNames:
      - prow-controller-manager-leader-lock
    verbs:
      - get
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - prow-controller-manager-leader-lock
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - create
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-controller-manager-for-test
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
      - watch
      - create
      - patch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prow-controller-manager
subjects:
  - kind: ServiceAccount
    name: prow-controller-manager
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-controller-manager-for-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prow-controller-manager-for-test
subjects:
  - kind: ServiceAccount
    name: prow-controller-manager
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: prow-crier
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-crier
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - "prowjobs"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "patch"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-crier-for-test
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "events"
    verbs:
      - "get"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "patch"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-crier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prow-crier
subjects:
  - kind: ServiceAccount
    name: prow-crier
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-crier-for-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prow-crier-for-test
subjects:
  - kind: ServiceAccount
    name: prow-crier
